language: bash
services: docker
fast_finish: true
env:
    - "PHP=7.1 DB=oracle SUITE=phpunit"
    - "PHP=7.0 DB=mssql SUITE=phpunit"
    - "PHP=7.1 DB=oracle SUITE=behat BROWSER=chrome"
    - "PHP=7.0 DB=mssql SUITE=behat BROWSER=firefox"

install:
    - git clone --depth 1 https://github.com/moodlehq/moodle-docker.git $HOME/moodle-docker
    - cd $HOME/moodle-docker

before_script:
    - export MOODLE_DOCKER_WWWROOT=$TRAVIS_BUILD_DIR;
    - cp config.docker-template.php $MOODLE_DOCKER_WWWROOT/config.php;
    - export MOODLE_DOCKER_DB=$DB;
    - export MOODLE_DOCKER_PHP_VERSION=$PHP;
    - export MOODLE_DOCKER_BROWSER=$BROWSER;
    - bin/moodle-docker-compose up -d;
    - bin/moodle-docker-wait-for-db
    - >
        if [ "$SUITE" = 'phpunit' ];
        then
            bin/moodle-docker-compose exec -T webserver php admin/tool/phpunit/cli/init.php
        fi
    - >
        if [ "$SUITE" = 'behat' ];
        then
            bin/moodle-docker-compose exec -T webserver php admin/tool/behat/cli/init.php
        fi

script:
    - >
        if [ "$SUITE" = 'phpunit' ];
        then
            bin/moodle-docker-compose exec -T webserver vendor/bin/phpunit --testsuite=mod_workshop_testsuite
        fi
    - >
        if [ "$SUITE" = 'behat' ];
        then
            bin/moodle-docker-compose exec -T webserver php admin/tool/behat/cli/run.php --tags=@mod_workshop
        fi

after_script:
    - bin/moodle-docker-compose down

