build: false
shallow_clone: true
platform:
  - x86
#  - x64
clone_folder: c:\projects\moodle

install:
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd C:\projects\moodle
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction
  - php admin\tool\phpunit\cli\init.php



test_script:
    - cd c:\projects\moodle
    - vendor/bin/phpunit
